### ISSUE TITLE
Adicionar section de encontros (meetups) 

### ISSUE THREAD

**Issue by fredericksilva** [pythonrio/pythonrio.github.io#1]
Adicionar uma section com agenda de encontros do PythOnRio.
Adicionar irc, slack ou a lista de discussão do grupo.

**Comment by GuidoBR** [comment]
Acredito que a página de [eventos](http://pythonrio.github.io/events/)  e o PR #23 resolvem essa issue.

**Comment by fredericksilva** [comment]
Sim, Saudades mestre @GuidoBR  ^^
