### ISSUE TITLE
Automatizar geração do site estático usando Travis-CI

### ISSUE THREAD

**Issue by lucianoratamero** [pythonrio/pythonrio.github.io#14]
Seria legal ter uma estrutura em que pudéssemos simplesmente aceitar um PR e o site novo ser gerado automaticamente.
No meu blog, que é em Lektor também, fiz isso com Travis-CI, seguindo essa documentação aqui:
[https://www.getlektor.com/docs/deployment/travisci/](https://www.getlektor.com/docs/deployment/travisci/)

**Comment by darlenedms** [comment]
Feito em 35d115f817481d30bfb8f4a9bc7f22ef0c655ef0 e 9d128eb9827f142965c47ed4845c75a9cd30708c

**Comment by pgrangeiro** [comment]
@darlenedms mas como ficou o deploy? mudou pro ghpages mesmo?

**Comment by pgrangeiro** [comment]
esquece. agora que eu lir a descrição do commit kk
