### ISSUE TITLE
Atualizar área de Parceiros

### ISSUE THREAD

**Issue by berinhard** [pythonrio/pythonrio.github.io#16]
Acho justo mantermos a área de parceiros de acordo com o encontro em si e não com o histórico de apoio ao encontro. Isso funciona como argumento de "venda" quando formos tentar parcerias para próximas edições.

**Comment by GuidoBR** [comment]
Quais são os parceiros dessa edição? INFNET e mais quem?

**Comment by pgrangeiro** [comment]
Só o INFNET

**Comment by douglasbastos** [comment]
Seria legal então uma página para cada evento com o próximo na home, assim poderiamos manter um histórico.

Exemplo:
http://pythonrio.github.io/6

**Comment by pgrangeiro** [comment]
Concordo com a ideia do @douglasbastos

**Comment by dvl** [comment]
Lembrei agora, foi exatamente por isso que tinha começado uma versão com Django um tempo atrás, pra poder manter esse histórico. https://github.com/pythonrio/pyrio

**Comment by douglasbastos** [comment]
@dvl Bem deve ter como fazer isso pelo lektor tb.

Criei um issue para essa projeto antigo.
https://github.com/pythonrio/pyrio/issues/6

**Comment by berinhard** [comment]
:+1: para fazer pelo lektor
