### ISSUE TITLE
Mapa não carrega

### ISSUE THREAD

**Issue by dvl** [pythonrio/pythonrio.github.io#21]
Testei no Chrome e no Firefox, a jquery está carregada na página.

![2016-02-17-180923_665x263_scrot](https://cloud.githubusercontent.com/assets/308337/13123182/35ef18ea-d5a2-11e5-985c-095274383c6a.png)

![2016-02-17-181414_426x137_scrot](https://cloud.githubusercontent.com/assets/308337/13123195/46689d7c-d5a2-11e5-8b06-ff75f1392eca.png)

**Comment by lucianoratamero** [comment]
Provavelmente problema de ordem de importação. A jQuery deve estar sendo importada depois desse arquivo.

-- 
Luciano Ratamero

Em 17 de fevereiro de 2016 no 18:14:35, André Luiz (notifications@github.com) escreveu:

Testei no Chrome e no Firefox, a jquery está carregada na página.

**Comment by darlenedms** [comment]
Quais versões?
Testei no OS X 10.10.5 com o Chrome 48.0.2564.97 (64-bit), Firefox 44.0.2 e FirefoxDeveloperEdition 46.0a2 e todos funcionaram.

@lucianoratamero conseguiu reproduzir?

**Comment by darlenedms** [comment]
Consegui reproduzir, o problema é quando você acessa via https, vou dar uma olhada no que pode ser feito.

<img width="1280" alt="screen shot 2016-02-17 at 6 42 09 pm" src="https://cloud.githubusercontent.com/assets/850280/13124010/411c88b6-d5a6-11e5-8837-64a6906c9d04.png">

**Comment by darlenedms** [comment]
@dvl Veja agora se está funcionando.

**Comment by dvl** [comment]
Perfeito :) 

No FF e Chrome.
