### ISSUE TITLE
Adicionar Código de Conduta da comunidade

### ISSUE THREAD

**Issue by mondaini** [pythonrio/pythonrio.github.io#24]

**Comment by mondaini** [comment]
temos algum modelo prévio?

**Comment by GuidoBR** [comment]
Tem o da Associação Python Brasil - https://github.com/pythonbrasil/codigo-de-conduta

**Comment by berinhard** [comment]
Não tinha visto essa issue, perdão e acabou gerando um trabalho pro @rtancman. Enfim, comentei no PR minha visão sobre a necessidade do CdC neste momento.
