### ISSUE TITLE
Mudar home para ser uma página de info

### ISSUE THREAD

**Issue by berinhard** [pythonrio/pythonrio.github.io#31]
Hoje a home do evento é sempre sobre o meetup e não sobre a comunidade. Acho que vale tornar a página bem genérica, só com uma leve descrição e alguns links (facebook, telegram, lista do yahoo e útlimos encontros).

Daí, sempre que surgir um novo, é só adicionar o link pro próximo encontro e a home em si não fica desatualizada.

**Comment by rtancman** [comment]
Segue a proposta da nova home para o pythonrio.

![proposta_nova_home_pythonrio](https://cloud.githubusercontent.com/assets/596684/20436374/2bb534a4-ad97-11e6-85eb-d47a5806e78f.png)

**Comment by pgrangeiro** [comment]
que isso ein, ficou lindimais 👍
