### ISSUE TITLE
Adicionar link de inscrição

### ISSUE THREAD

**Issue by Delermando** [pythonrio/pythonrio.github.io#39]
Substituir o botão "Inscrições em breve!" por "Inscrições" 
E adicionar o com o link para inscrições 
https://www.eventbrite.com/e/xi-encontro-pythonrio-registration-26495497747

**Comment by pgrangeiro** [comment]
Feito em [c3841b9cccc040f2c5da9a96b6170abdea1d7550](https://github.com/pythonrio/pythonrio.github.io/commit/c3841b9cccc040f2c5da9a96b6170abdea1d7550)
